export const CREATE_WISHLIST = "CREATE_WISHLIST";
export const GET_WISHLIST = "GET_WISHLIST";
export const UPDATE_WISHLIST = "UPDATE_WISHLIST";
export const DELETE_WISHLIST = "DELETE_WISHLIST";
export const WISHLIST_ERROR = "WISHLIST_ERROR";